Changed notebook to .py file
HSE-JetBrains-department/2022_similar_dev_search_kononov pull request #3
Opened 2022-02-25 12:19 UTC by Alex5041

2022-02-25 14:56 UTC, EgorBu requested changes
Great work! Let's improve it a bit more)

2022-02-25 14:56 UTC, EgorBu commented on main.py
> +from dulwich.repo import Repo
pep8 - order imports alphabetically

2022-02-25 14:56 UTC, EgorBu commented on main.py
> +    get amount of added and deleted lines
Let's start docstring with capital letter

2022-02-25 14:56 UTC, EgorBu commented on main.py
> +    :param change: change of file
let's look at `TreeChange` description to give better explanation here

2022-02-25 14:56 UTC, EgorBu commented on main.py
> +    :return: added number, deleted number
number of rows added/deleted

2022-02-25 14:56 UTC, EgorBu commented on main.py
> +        if j[0] == '+' and j[1] != '+':
let's use double quotes everywhere

2022-02-25 14:56 UTC, EgorBu commented on main.py
> +            del res[path]
handling of binary or corrupted files

2022-02-25 14:56 UTC, EgorBu commented on main.py
> +    res = {}
let's use `defaultdict`
```suggestion
    res = defaultdict(dict)
```

so you can do
```python
res[some_key][another_key] = some_value
```

2022-02-25 14:56 UTC, EgorBu commented on main.py
> +        res[path] = {}
and we can delete it
```suggestion
```

2022-02-25 14:56 UTC, EgorBu commented on main.py
> +    :return: repository in a dictionary form
it doesn't match return typing

2022-02-25 14:56 UTC, EgorBu commented on main.py
> +    for c in repo.get_walker():
it could be parallelized + let's call it at least entry

2022-02-25 14:56 UTC, EgorBu commented on main.py
> +repo_to_json('scikit-learn', 'https://github.com/scikit-learn/scikit-learn', 'res2.json')
let's delete it and make CLI

2022-02-25 14:56 UTC, EgorBu commented on main.py
> +repo_to_json('scikit-learn', 'https://github.com/scikit-learn/scikit-learn', 'res2.json')
CLI related functionality could be separated into another file

2022-02-25 14:56 UTC, EgorBu commented on GitDevSearch.ipynb
> +{
you can delete this notebook + make interactive rebase to delete commit

2022-03-04 11:28 UTC, EgorBu requested changes
Good! Let's improve it a bit more - and make 1 more iteration of review

2022-03-04 11:28 UTC, EgorBu commented on extract.py
> +    Get amount of added and deleted lines
`Get number`

2022-03-04 11:28 UTC, EgorBu commented on extract.py
> +    diffs = d.compare(repo.get_object(change.old.sha).data.decode().splitlines(),
you can make lambda like `into_lines = lambda sha: repo.get_object(sha).data.decode().splitlines()` - so logic is not duplicated

2022-03-04 11:28 UTC, EgorBu commented on extract.py
> +def get_diff(repo: Repo, entry: WalkEntry) -> dict:
let's use `Dict` from `typing`

2022-03-04 11:28 UTC, EgorBu commented on extract.py
> +def get_diff(repo: Repo, entry: WalkEntry) -> dict:
so you will have something like `Dict[str, int]`

2022-03-04 11:28 UTC, EgorBu commented on extract.py
> +    for c in entry.changes():
let's use meaningful names

2022-03-04 11:28 UTC, EgorBu commented on extract.py
> +                res[path]["blob_id"] = str(repo.get_object(c.old.sha).id.decode())
let's always use information from `new`

2022-03-04 11:28 UTC, EgorBu commented on extract.py
> +                res[path]["blob_id"] = str(repo.get_object(c.old.sha).id.decode())
it should be `c.new.sha`

2022-03-04 11:28 UTC, EgorBu commented on extract.py
> +                res[path]["deleted"] = len(repo.get_object(c.old.sha).data.decode().splitlines())
let's use lambda for such complicated logic to avoid problems in future - you can modify one line and forget to modify another or something like this

2022-03-04 11:28 UTC, EgorBu commented on extract.py
> +        except UnicodeDecodeError:
let's add logging - repository, commit, old/new path, etc

2022-03-04 11:28 UTC, EgorBu commented on extract.py
> +                res.append(commit)
it could lead to OOM errors in future for big repositories - let's use generator `yield`

2022-03-04 11:28 UTC, EgorBu commented on extract.py
> +def form(repo: Repo, url: str) -> List:
let's rename to `get_authors_stats` or something like this - `form` isn't very specific name

2022-03-04 11:28 UTC, EgorBu commented on extract.py
> +    with open(json_name, "w") as f:
let's use `jsonl` format - where each row is valid `json`

2022-03-04 11:28 UTC, EgorBu commented on script.py
> +parser = argparse.ArgumentParser(description="Extract repository.")
let's wrap into 
```python
if __name__ == "__main__":
    parser = ...
```

2022-03-18 11:15 UTC, EgorBu requested changes
Almost there! Let's polish a bit and merge

2022-03-18 11:15 UTC, EgorBu commented on extract.py
> +def is_binary(repo, change) -> bool:
let's add typings

2022-03-18 11:15 UTC, EgorBu commented on extract.py
> +def into_lines(repo: Repo, sha: bytes) -> List[str]:
docstring is missing

2022-03-18 11:15 UTC, EgorBu commented on extract.py
> +
```suggestion
```

2022-03-18 11:15 UTC, EgorBu commented on extract.py
> +
```suggestion
```

2022-03-18 11:15 UTC, EgorBu commented on extract.py
> +
```suggestion
```

2022-03-18 11:15 UTC, EgorBu commented on extract.py
> +        # Handling corrupted files
let's move comment about exception handling into `except UnicodeDecodeError as e:`

2022-03-18 11:15 UTC, EgorBu commented on extract.py
> +        path = (change.new.path or change.old.path).decode()
let's delete this line and provide `path` according to availability
```python
if change.old.sha is None:
    process_only_blob(..., change.new.path, res, "deleted", "added")
elif change.new.sha is None:
    process_only_blob(..., change.old.path, res, "deleted", "added")
```

2022-03-18 11:15 UTC, EgorBu commented on extract.py
> +            logger.error(f"exception in repository: {repo.path}, file: {path}, cause: {e}")
Let's start error log with capital letter
```suggestion
            logger.error(f"Exception in repository: {repo.path}, file: {path}, cause: {e}")
````

2022-03-18 11:15 UTC, EgorBu commented on extract.py
> +
delete empty line - please do it everywhere

2022-03-18 11:15 UTC, EgorBu commented on extract.py
> +            file.write(json.dumps(commit))
`json.dumps(commit) + "\n"` - you can simplify it a bit

2022-03-18 11:15 UTC, EgorBu commented on script.py
> +    parser.add_argument("repo_name", type=str, help="name of extracted repository")
* description should start with upper case
* `repo_name` - let's use `-` instead of `_`
* let's provide shortening - like `-r` for `--repo-name`

2022-03-18 11:15 UTC, EgorBu commented on script.py
> +    repo_to_jsonl(args.repo_name, args.repo_url, args.json_name)
new line

2022-03-18 11:15 UTC, EgorBu commented on stargazers.py
> +def get_repo(repo_name: str,
let's make `max-line-length=99`

2022-03-18 11:15 UTC, EgorBu commented on stargazers.py
> +
delete

2022-03-18 11:15 UTC, EgorBu commented on stargazers.py
> +    time.sleep(max(0.001, reset_timestamp - calendar.timegm(time.gmtime())))
```suggestion
    time.sleep(max(0, reset_timestamp - calendar.timegm(time.gmtime())))
```

2022-03-18 11:15 UTC, EgorBu commented on stargazers.py
> +        raise ValueError("you should specify access_token or token_env_key")
Let's start with capital letter

2022-03-18 11:15 UTC, EgorBu commented on stargazers.py
> +    i = 0
let's use meaningful names

2022-03-18 11:15 UTC, EgorBu commented on stargazers.py
> +            logger.exception(f"unexpected exception - {e}")
this should not happen - let's delete so broad exception handling

2022-04-22 11:07 UTC, EgorBu requested changes
Good job! Let's polish it a bit more!)

2022-04-22 11:07 UTC, EgorBu commented on extract.py
> +from typing import List, Tuple, Dict, Any, Generator
alphabetic order of imports please

2022-04-22 11:07 UTC, EgorBu commented on extract.py
> +        return str(e).startswith("'utf-8' codec can't decode byte")
this could be `False`

2022-04-22 11:07 UTC, EgorBu commented on extract.py
> +        return str(e).startswith("'utf-8' codec can't decode byte")
please read [this](https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/) - probably you can add dependency to detect [binary or not](https://binaryornot.readthedocs.io/en/latest/readme.html#why)

2022-04-22 11:07 UTC, EgorBu commented on extract.py
> +    for i in diffs:
let's use meaningful names instead of `i`

2022-04-22 11:07 UTC, EgorBu commented on extract.py
> +                process_only_blob(repo, change.new.sha, change.new.path.decode(), res, "deleted",
let's use named arguments - too many arguments - here could be a mistake

2022-04-22 11:07 UTC, EgorBu commented on extract.py
> +                process_only_blob(repo, change.new.sha, change.new.path.decode(), res, "deleted",
```python
process_only_blob(repo=repo, sha=change.new.sha, ...)
```

2022-04-22 11:07 UTC, EgorBu commented on extract.py
> +    :return: repository in a list form
return definition differs from typing and code - let's synchronize them

2022-04-22 11:07 UTC, EgorBu commented on script.py
> +def add_extract_command(subparsers_action: argparse.Action):
docstring is missing

2022-04-29 11:43 UTC, EgorBu requested changes
Nice job! Almost done!

2022-04-29 11:43 UTC, EgorBu commented on extract.py
> +        if diff[0] == "+" and diff[1] != "+":
please check that we don't lose any rows like `diff[0] == "+" and diff[1] == "+"`

2022-04-29 11:43 UTC, EgorBu commented on extract.py
> +def process_only_blob(repo: Repo, sha: bytes, path: str, change_dict: defaultdict, missing: str,
let's rename to `update_something` - because you are updating `change_dict`

2022-04-29 11:43 UTC, EgorBu commented on extract.py
> +        save_to_json(commit, json_path)
```suggestion
    with open(filepath) as f:
        for commit in get_repo_changes(repo, url):
            save_to_json(commit, f)
```

2022-04-29 11:43 UTC, EgorBu commented on extract.py
> +def save_to_json(data, json_path: str):
please change accordingly to function `repo_to_json`

2022-04-29 11:43 UTC, EgorBu commented on script.py
> +        save_to_json(extract_stargazers(args.repo_path,
let's use named arguments

2022-05-06 10:23 UTC, waterstopper commented on extract.py
> +        if diff[0] == "+" and diff[1] != "+":
In [documentation](https://docs.python.org/3/library/difflib.html#difflib.Differ.compare) and by debugging I couldn't find a case where line startswith `"++"`.
 
 Seems that second check `and diff[1] != "+"` is useless

2022-05-13 12:49 UTC, EgorBu approved these changes
Nice!

2022-05-13 12:50 UTC, merged